spring.application.name=risk-monitor-backend

spring.datasource.url=jdbc:postgresql://localhost:5433/risk_monitor
spring.datasource.username=dev_user
spring.datasource.password=dev_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

risk-monitor.system.user=system

# SPECIALIZATION DEMO: COMMENT -> GOOGLE LOGIN, UNCOMMENT -> LOCAL LOGIN
spring.profiles.active=local

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true

# Business operation audit logging
risk-monitor.audit.enabled=true
